## 基础应用配置
spring:
  application.name: ${projectName}
  output.ansi.enabled: always
server:
  port: 8080
  servlet.context-path: /${projectName}

## 简单log日志级别配置,如果有详细配置,请到xml/logback-spring.xml中配置
logging:
  level:
    root: info

## 集成中间件服务配置(根据工程需要选择性开关)
spring.profiles.include: db,kafka,job,cloud